vich_uploader:
    db_driver: orm
    mappings:
        images_directory:
            uri_prefix: '%images_directory%'
            upload_destination: '%kernel.project_dir%/public%images_directory%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: false
        attachments:
            uri_prefix: '%attachments%'
            upload_destination: '%kernel.project_dir%/public%attachments%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: false


