<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFaxBSiu\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFaxBSiu/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerFaxBSiu.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerFaxBSiu\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerFaxBSiu\App_KernelProdContainer([
    'container.build_hash' => 'FaxBSiu',
    'container.build_id' => '4bd854f3',
    'container.build_time' => 1650214471,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFaxBSiu');
