<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerW73HecJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerW73HecJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerW73HecJ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerW73HecJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerW73HecJ\App_KernelDevDebugContainer([
    'container.build_hash' => 'W73HecJ',
    'container.build_id' => '5b01d8f9',
    'container.build_time' => 1650205119,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerW73HecJ');
