<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.9a71ee5d.js',
                '/build/484.cd95c96d.js',
                '/build/app.50ab8ef8.js',
            ],
            'css' => [
                '/build/app.b7ce1eed.css',
            ],
        ],
    ],
],

]];
