<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class HotelRooms extends \App\Entity\HotelRooms implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\HotelRooms' . "\0" . 'id', '' . "\0" . 'App\\Entity\\HotelRooms' . "\0" . 'title', '' . "\0" . 'App\\Entity\\HotelRooms' . "\0" . 'description', '' . "\0" . 'App\\Entity\\HotelRooms' . "\0" . 'price', '' . "\0" . 'App\\Entity\\HotelRooms' . "\0" . 'booking_link', '' . "\0" . 'App\\Entity\\HotelRooms' . "\0" . 'file', '' . "\0" . 'App\\Entity\\HotelRooms' . "\0" . 'images', '' . "\0" . 'App\\Entity\\HotelRooms' . "\0" . 'reservation_rooms', '' . "\0" . 'App\\Entity\\HotelRooms' . "\0" . 'hotels', '' . "\0" . 'App\\Entity\\HotelRooms' . "\0" . 'imageFile'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\HotelRooms' . "\0" . 'id', '' . "\0" . 'App\\Entity\\HotelRooms' . "\0" . 'title', '' . "\0" . 'App\\Entity\\HotelRooms' . "\0" . 'description', '' . "\0" . 'App\\Entity\\HotelRooms' . "\0" . 'price', '' . "\0" . 'App\\Entity\\HotelRooms' . "\0" . 'booking_link', '' . "\0" . 'App\\Entity\\HotelRooms' . "\0" . 'file', '' . "\0" . 'App\\Entity\\HotelRooms' . "\0" . 'images', '' . "\0" . 'App\\Entity\\HotelRooms' . "\0" . 'reservation_rooms', '' . "\0" . 'App\\Entity\\HotelRooms' . "\0" . 'hotels', '' . "\0" . 'App\\Entity\\HotelRooms' . "\0" . 'imageFile'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (HotelRooms $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getImageFile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageFile', []);

        return parent::getImageFile();
    }

    /**
     * {@inheritDoc}
     */
    public function setImageFile(\Symfony\Component\HttpFoundation\File\File $file = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImageFile', [$file]);

        return parent::setImageFile($file);
    }

    /**
     * {@inheritDoc}
     */
    public function getFile(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFile', []);

        return parent::getFile();
    }

    /**
     * {@inheritDoc}
     */
    public function setFile(string $file = NULL): \App\Entity\HotelRooms
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFile', [$file]);

        return parent::setFile($file);
    }

    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', []);

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle(string $title): \App\Entity\HotelRooms
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', [$title]);

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription(string $description): \App\Entity\HotelRooms
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrice(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrice', []);

        return parent::getPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrice(string $price): \App\Entity\HotelRooms
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrice', [$price]);

        return parent::setPrice($price);
    }

    /**
     * {@inheritDoc}
     */
    public function getBookingLink(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBookingLink', []);

        return parent::getBookingLink();
    }

    /**
     * {@inheritDoc}
     */
    public function setBookingLink(string $booking_link): \App\Entity\HotelRooms
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBookingLink', [$booking_link]);

        return parent::setBookingLink($booking_link);
    }

    /**
     * {@inheritDoc}
     */
    public function getImages(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImages', []);

        return parent::getImages();
    }

    /**
     * {@inheritDoc}
     */
    public function addImage(\App\Entity\Images $image): \App\Entity\HotelRooms
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addImage', [$image]);

        return parent::addImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function removeImage(\App\Entity\Images $image): \App\Entity\HotelRooms
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeImage', [$image]);

        return parent::removeImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getReservationRooms(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReservationRooms', []);

        return parent::getReservationRooms();
    }

    /**
     * {@inheritDoc}
     */
    public function addReservationRoom(\App\Entity\ReservationRooms $reservationRoom): \App\Entity\HotelRooms
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addReservationRoom', [$reservationRoom]);

        return parent::addReservationRoom($reservationRoom);
    }

    /**
     * {@inheritDoc}
     */
    public function removeReservationRoom(\App\Entity\ReservationRooms $reservationRoom): \App\Entity\HotelRooms
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeReservationRoom', [$reservationRoom]);

        return parent::removeReservationRoom($reservationRoom);
    }

    /**
     * {@inheritDoc}
     */
    public function getHotels(): ?\App\Entity\Hotels
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHotels', []);

        return parent::getHotels();
    }

    /**
     * {@inheritDoc}
     */
    public function setHotels(?\App\Entity\Hotels $hotels): \App\Entity\HotelRooms
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHotels', [$hotels]);

        return parent::setHotels($hotels);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

}
